### ISSUE TITLE
能不能增加越界回弹

### ISSUE THREAD

**Issue by zhonghq** [dlhandsome/we-cropper#10]
这是一个很必要的功能，没有这个各种不方便的说。
还有，使用开发工具生成的图片比例不对

**Comment by dlhandsome** [comment]
谢谢反馈
防止越界会在下一个版本加上
关于图片比例不对，真机上显示正常的话，那应该是没问题的，开发工具和实际真机有一定差异性。

**Comment by dlhandsome** [comment]
@zhonghq @lishuminjames @03128crz @KameraSui

**Comment by dlhandsome** [comment]
@zhonghq 目前已支持防止越界，回弹效果暂不实现
