### ISSUE TITLE
请问能否支持获取图片的base64？还有能否支持把图片裁剪成圆形？

### ISSUE THREAD

**Issue by mkanako** [dlhandsome/we-cropper#15]

**Comment by dlhandsome** [comment]
具体场景？

**Comment by mkanako** [comment]
@dlhandsome 小程序不支持同时上传多张图片，于是就想获取图片的base64来实现上传多张图片，不过看文档小程序好像也不支持😂
圆形这个是我需要把用户上传的图片裁成圆形然后再跟其他图片合并成一张图，现在是在服务端裁剪的，我是希望能在小程序直接裁成圆形更加方便点，不过这个需求可能比较小众哈

**Comment by dlhandsome** [comment]
目前小程序不支持获取图片base64，也暂无好的方法实现圆形裁剪，T T
