### ISSUE TITLE
选择原图（2.9M）的文件，发现画布显示不了图片

### ISSUE THREAD

**Issue by wangxiaochuang** [dlhandsome/we-cropper#2]
选择原图（2.9M）的文件，发现画布显示不了图片

**Comment by Mrjen** [comment]
src设置的是同一域名下的图片，但是canvas显示不出来图片，程序报错不在合法域名下，在wxml里面创建image标签图片就可以出来

**Comment by dlhandsome** [comment]
方便发一下细节code以及报错信息？

**Comment by dlhandsome** [comment]
@wangxiaochuang 应该是小程序限制了绘制图片的大小，通常小于1M的图片都能绘制出来，建议采用压缩模式上传

**Comment by dlhandsome** [comment]
@Mrjen 你尝试下用wx.getImageInfo这个方法，获取图片的本地路径，然后传入

**Comment by wangxiaochuang** [comment]
@dlhandsome 使用压缩模式就可以了~

**Comment by dlhandsome** [comment]
@Mrjen 这个问题已修复

**Comment by gjycdd** [comment]
测试过了，原图3.9M，压缩后600K+，<700K，无法显示，500K以下可正常显示，可能是我机子问题？小米MIX2，Android7.1.1

**Comment by dlhandsome** [comment]
如果压缩后还draw不出来，那只能去小程序官方论坛提个bug了
