### ISSUE TITLE
上传图片之后要手指移动才显示裁剪框

### ISSUE THREAD

**Issue by sleepwood** [dlhandsome/we-cropper#23]
首先是全部显示图片 要手指移动一下才能显示裁剪框

我试过在上传图片更新canvas 但是不成功 还是会先全部显示

但是用手指移动一下就好了 我觉得是不是 self.updateCanvas(); 添加错地方了

**Comment by dlhandsome** [comment]
我用我手机试了下，没有问题的，你可以按照example中的局部裁剪

如果还存在这种情况，可以参照[Wiki](https://github.com/dlhandsome/we-cropper/wiki/Issues%E9%A1%BB%E7%9F%A5)编辑一下issue，便于我定位

**Comment by sleepwood** [comment]
又在机器上测试了一下 没有这个问题了 可能是开发工具的问题
