### ISSUE TITLE
想在new weCroper()时调用pushOrign将图片显示出来该如何处理

### ISSUE THREAD

**Issue by 03128crz** [dlhandsome/we-cropper#6]
new weCropper(data)
      .on('ready', function (ctx) {
        console.log(`wecropper is ready for work!`)
      })
      .on('beforeImageLoad', (ctx) => {
        console.log(`before picture loaded, i can do something`)
        console.log(`current canvas context:`, ctx)
        wx.showToast({
          title: '上传中',
          icon: 'loading',
          duration: 20000
        })
      })
      .on('imageLoad', (ctx) => {
        console.log(`picture loaded`)
        console.log(`current canvas context:`, ctx)
        wx.hideToast()
      })

**Comment by dlhandsome** [comment]
参考文档：[两种方式载入图片](https://dlhandsome.github.io/we-cropper/#/?id=%e7%a4%ba%e4%be%8b)
