### ISSUE TITLE
你好，我下载了你的demo，运行时报错，不知道这个错是啥意思，看起来像是跨域

### ISSUE THREAD

**Issue by lishuminjames** [dlhandsome/we-cropper#9]
VM122:2 Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Error (native)
    at Object.invokeCanvasToDataUrl_100088 (http://1397529163.debug.open.weixin.qq.com/example/network/network.html:24:10842)
    at u (<anonymous>:1:2257)
    at <anonymous>:1:4644

**Comment by dlhandsome** [comment]
嗯，你把开发工具的域名校验关掉试试，生产环境必须是加载安全域名下的图片

**Comment by lishuminjames** [comment]
我开发环境都是不校验域名的，不是这个原因

**Comment by dlhandsome** [comment]
问题解决没？或者加我微信说
<img src="https://github.com/dlhandsome/we-cropper/blob/master/docs/assets/wechat.jpg?raw=true" width="150" height="150" />

**Comment by lishuminjames** [comment]
解决了，并不是代码问题，是我的开发工具没更新，不支持基础库1.1.2的调试，谢谢楼主
